
nimon:
  key: ???
  url: http://127.0.0.1/nii/public/htdocs/hosting/server/monitor

mysql:
  host: localhost
  user: root
  password: ''
  slave: true

apache:
  statusUrl: http://127.0.0.1/server-status?auto

logging: default

